# -*- coding: utf-8 -*-
"""Módulo_para_Coleta_de_Dados_via_APIs_com_Python_Walter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wtmoaWwB-WovDMcReiRdbmff68K0sKlS
"""

# Walter Moura Alcantara - JC3003213

import requests

def getPokemon(*pokemonIds):
  result = []
  url = 'https://pokeapi.co/api/v2/pokemon/'

  for pokemonId in pokemonIds:
    response = requests.get(url + str(pokemonId))
    data = response.json()

    result.append(data['name'])

  return result

pokemonIdList = [1, 72, 3, 44, 9, 36]

getPokemon(*pokemonIdList)